### ISSUE TITLE
implement new subscription dialog

### ISSUE THREAD

**Issue by nucleus-ffm** [nucleus-ffm/foss_warn#130]
we need a new subscription dialog, based on a map to select places worldwide

### subtasks
- [x] add map view
- [ ] add OSM nominatim to search for places or find a api where we can use auto completion
   - [ ] create custom HTTP client with useragent
- [ ] implement loading screen
  - [x] first implementation
  - [ ] clean implementation
- [ ] add error handling
